/* Generated by Wayland scanner 1.25.0 */

/*
 * Copyright © 2008-2013 Kristian Høgsberg
 * Copyright © 2013      Rafael Antognolli
 * Copyright © 2013      Jasper St. Pierre
 * Copyright © 2010-2013 Intel Corporation
 * Copyright © 2015-2017 Samsung Electronics Co., Ltd
 * Copyright © 2015-2017 Red Hat Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include "perimortem/platform/wayland/xdg_shell.hpp"

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <wayland-client.h>

#include "wayland-util.h"

#ifndef __has_attribute
#define __has_attribute(x) 0 /* Supports other compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface xdg_popup_interface;
extern const struct wl_interface xdg_positioner_interface;
extern const struct wl_interface xdg_surface_interface;
extern const struct wl_interface xdg_toplevel_interface;

static const struct wl_interface* xdg_shell_types[] = {
  NULL,
  NULL,
  NULL,
  NULL,
  &xdg_positioner_interface,
  &xdg_surface_interface,
  &wl_surface_interface,
  &xdg_toplevel_interface,
  &xdg_popup_interface,
  &xdg_surface_interface,
  &xdg_positioner_interface,
  &xdg_toplevel_interface,
  &wl_seat_interface,
  NULL,
  NULL,
  NULL,
  &wl_seat_interface,
  NULL,
  &wl_seat_interface,
  NULL,
  NULL,
  &wl_output_interface,
  &wl_seat_interface,
  NULL,
  &xdg_positioner_interface,
  NULL,
};

static const struct wl_message xdg_wm_base_requests[] = {
  {"destroy", "", xdg_shell_types + 0},
  {"create_positioner", "n", xdg_shell_types + 4},
  {"get_xdg_surface", "no", xdg_shell_types + 5},
  {"pong", "u", xdg_shell_types + 0},
};

static const struct wl_message xdg_wm_base_events[] = {
  {"ping", "u", xdg_shell_types + 0},
};

extern WL_PRIVATE const struct wl_interface xdg_wm_base_interface = {
  "xdg_wm_base", 7, 4, xdg_wm_base_requests, 1, xdg_wm_base_events,
};

static const struct wl_message xdg_positioner_requests[] = {
  {"destroy", "", xdg_shell_types + 0},
  {"set_size", "ii", xdg_shell_types + 0},
  {"set_anchor_rect", "iiii", xdg_shell_types + 0},
  {"set_anchor", "u", xdg_shell_types + 0},
  {"set_gravity", "u", xdg_shell_types + 0},
  {"set_constraint_adjustment", "u", xdg_shell_types + 0},
  {"set_offset", "ii", xdg_shell_types + 0},
  {"set_reactive", "3", xdg_shell_types + 0},
  {"set_parent_size", "3ii", xdg_shell_types + 0},
  {"set_parent_configure", "3u", xdg_shell_types + 0},
};

extern WL_PRIVATE const struct wl_interface xdg_positioner_interface = {
  "xdg_positioner", 7, 10, xdg_positioner_requests, 0, NULL,
};

static const struct wl_message xdg_surface_requests[] = {
  {"destroy", "", xdg_shell_types + 0},
  {"get_toplevel", "n", xdg_shell_types + 7},
  {"get_popup", "n?oo", xdg_shell_types + 8},
  {"set_window_geometry", "iiii", xdg_shell_types + 0},
  {"ack_configure", "u", xdg_shell_types + 0},
};

static const struct wl_message xdg_surface_events[] = {
  {"configure", "u", xdg_shell_types + 0},
};

extern WL_PRIVATE const struct wl_interface xdg_surface_interface = {
  "xdg_surface", 7, 5, xdg_surface_requests, 1, xdg_surface_events,
};

static const struct wl_message xdg_toplevel_requests[] = {
  {"destroy", "", xdg_shell_types + 0},
  {"set_parent", "?o", xdg_shell_types + 11},
  {"set_title", "s", xdg_shell_types + 0},
  {"set_app_id", "s", xdg_shell_types + 0},
  {"show_window_menu", "ouii", xdg_shell_types + 12},
  {"move", "ou", xdg_shell_types + 16},
  {"resize", "ouu", xdg_shell_types + 18},
  {"set_max_size", "ii", xdg_shell_types + 0},
  {"set_min_size", "ii", xdg_shell_types + 0},
  {"set_maximized", "", xdg_shell_types + 0},
  {"unset_maximized", "", xdg_shell_types + 0},
  {"set_fullscreen", "?o", xdg_shell_types + 21},
  {"unset_fullscreen", "", xdg_shell_types + 0},
  {"set_minimized", "", xdg_shell_types + 0},
};

static const struct wl_message xdg_toplevel_events[] = {
  {"configure", "iia", xdg_shell_types + 0},
  {"close", "", xdg_shell_types + 0},
  {"configure_bounds", "4ii", xdg_shell_types + 0},
  {"wm_capabilities", "5a", xdg_shell_types + 0},
};

extern WL_PRIVATE const struct wl_interface xdg_toplevel_interface = {
  "xdg_toplevel", 7, 14, xdg_toplevel_requests, 4, xdg_toplevel_events,
};

static const struct wl_message xdg_popup_requests[] = {
  {"destroy", "", xdg_shell_types + 0},
  {"grab", "ou", xdg_shell_types + 22},
  {"reposition", "3ou", xdg_shell_types + 24},
};

static const struct wl_message xdg_popup_events[] = {
  {"configure", "iiii", xdg_shell_types + 0},
  {"popup_done", "", xdg_shell_types + 0},
  {"repositioned", "3u", xdg_shell_types + 0},
};

extern WL_PRIVATE const struct wl_interface xdg_popup_interface = {
  "xdg_popup", 7, 3, xdg_popup_requests, 3, xdg_popup_events,
};

using namespace Perimortem;

static auto as_proxy(void* handle) -> wl_proxy* {
  return static_cast<wl_proxy*>(handle);
}

static auto as_registry(void* handle) -> wl_registry* {
  return static_cast<wl_registry*>(handle);
}

static auto as_surface(void* handle) -> wl_surface* {
  return static_cast<wl_surface*>(handle);
}

Platform::Wayland::XdgShell::~XdgShell() {
  destroy();
}

auto Platform::Wayland::XdgShell::recognizes(const char* interface) -> Bool {
  return strcmp(interface, xdg_wm_base_interface.name) == 0;
}

auto Platform::Wayland::XdgShell::bind(void* registry, U32 name) -> Bool {
  if (wm_base) {
    return True;
  }

  wm_base = static_cast<wl_proxy*>(
      wl_registry_bind(as_registry(registry), name, &xdg_wm_base_interface, 1));
  if (!wm_base) {
    return False;
  }

  static ListenerFunction listener[] = {
    reinterpret_cast<ListenerFunction>(&Platform::Wayland::XdgShell::on_ping),
  };
  if (wl_proxy_add_listener(as_proxy(wm_base), listener, this) != 0) {
    wl_proxy_marshal_flags(
        as_proxy(wm_base), 0, nullptr, wl_proxy_get_version(as_proxy(wm_base)),
        WL_MARSHAL_FLAG_DESTROY);
    wm_base = nullptr;
    return False;
  }

  return True;
}

auto Platform::Wayland::XdgShell::create_toplevel(
    void* wayland_surface,
    const char* title,
    const char* application_id,
    Events new_events) -> Bool {
  if (!wm_base || surface || toplevel) {
    return False;
  }

  events = new_events;
  this->wayland_surface = wayland_surface;
  surface = wl_proxy_marshal_flags(
      as_proxy(wm_base), 2, &xdg_surface_interface,
      wl_proxy_get_version(as_proxy(wm_base)), 0, nullptr,
      as_surface(wayland_surface));
  if (!surface) {
    events = {};
    this->wayland_surface = nullptr;
    return False;
  }

  static ListenerFunction surface_listener[] = {
    reinterpret_cast<ListenerFunction>(
        &Platform::Wayland::XdgShell::on_surface_configure),
  };
  if (wl_proxy_add_listener(as_proxy(surface), surface_listener, this) != 0) {
    wl_proxy_marshal_flags(
        as_proxy(surface), 0, nullptr, wl_proxy_get_version(as_proxy(surface)),
        WL_MARSHAL_FLAG_DESTROY);
    surface = nullptr;
    events = {};
    this->wayland_surface = nullptr;
    return False;
  }

  toplevel = wl_proxy_marshal_flags(
      as_proxy(surface), 1, &xdg_toplevel_interface,
      wl_proxy_get_version(as_proxy(surface)), 0, nullptr);
  if (!toplevel) {
    wl_proxy_marshal_flags(
        as_proxy(surface), 0, nullptr, wl_proxy_get_version(as_proxy(surface)),
        WL_MARSHAL_FLAG_DESTROY);
    surface = nullptr;
    events = {};
    this->wayland_surface = nullptr;
    return False;
  }

  static ListenerFunction toplevel_listener[] = {
    reinterpret_cast<ListenerFunction>(
        &Platform::Wayland::XdgShell::on_toplevel_configure),
    reinterpret_cast<ListenerFunction>(
        &Platform::Wayland::XdgShell::on_toplevel_close),
    reinterpret_cast<ListenerFunction>(
        &Platform::Wayland::XdgShell::on_toplevel_configure_bounds),
    reinterpret_cast<ListenerFunction>(
        &Platform::Wayland::XdgShell::on_toplevel_wm_capabilities),
  };
  if (wl_proxy_add_listener(as_proxy(toplevel), toplevel_listener, this) != 0) {
    wl_proxy_marshal_flags(
        as_proxy(toplevel), 0, nullptr,
        wl_proxy_get_version(as_proxy(toplevel)), WL_MARSHAL_FLAG_DESTROY);
    toplevel = nullptr;
    wl_proxy_marshal_flags(
        as_proxy(surface), 0, nullptr, wl_proxy_get_version(as_proxy(surface)),
        WL_MARSHAL_FLAG_DESTROY);
    surface = nullptr;
    events = {};
    this->wayland_surface = nullptr;
    return False;
  }

  wl_proxy_marshal_flags(
      as_proxy(toplevel), 2, nullptr, wl_proxy_get_version(as_proxy(toplevel)),
      0, title);
  wl_proxy_marshal_flags(
      as_proxy(toplevel), 3, nullptr, wl_proxy_get_version(as_proxy(toplevel)),
      0, application_id);
  return True;
}

auto Platform::Wayland::XdgShell::destroy() -> void {
  if (toplevel) {
    wl_proxy_marshal_flags(
        as_proxy(toplevel), 0, nullptr,
        wl_proxy_get_version(as_proxy(toplevel)), WL_MARSHAL_FLAG_DESTROY);
    toplevel = nullptr;
  }

  if (surface) {
    wl_proxy_marshal_flags(
        as_proxy(surface), 0, nullptr, wl_proxy_get_version(as_proxy(surface)),
        WL_MARSHAL_FLAG_DESTROY);
    surface = nullptr;
  }

  if (wm_base) {
    wl_proxy_marshal_flags(
        as_proxy(wm_base), 0, nullptr, wl_proxy_get_version(as_proxy(wm_base)),
        WL_MARSHAL_FLAG_DESTROY);
    wm_base = nullptr;
  }

  events = {};
  wayland_surface = nullptr;
}

auto Platform::Wayland::XdgShell::on_ping(void*, void* shell, U32 serial)
    -> void {
  wl_proxy_marshal_flags(
      as_proxy(shell), 3, nullptr, wl_proxy_get_version(as_proxy(shell)), 0,
      serial);
}

auto Platform::Wayland::XdgShell::on_surface_configure(
    void* data,
    void* shell_surface,
    U32 serial) -> void {
  wl_proxy_marshal_flags(
      as_proxy(shell_surface), 4, nullptr,
      wl_proxy_get_version(as_proxy(shell_surface)), 0, serial);
  auto* shell = static_cast<Platform::Wayland::XdgShell*>(data);
  wl_surface_commit(as_surface(shell->wayland_surface));
}

auto Platform::Wayland::XdgShell::on_toplevel_configure(
    void* data,
    void*,
    S32 width,
    S32 height,
    void*) -> void {
  auto* shell = static_cast<Platform::Wayland::XdgShell*>(data);
  if (shell->events.configure) {
    shell->events.configure(shell->events.context, width, height);
  }
}

auto Platform::Wayland::XdgShell::on_toplevel_close(void* data, void*) -> void {
  auto* shell = static_cast<Platform::Wayland::XdgShell*>(data);
  if (shell->events.close) {
    shell->events.close(shell->events.context);
  }
}

auto Platform::Wayland::XdgShell::on_toplevel_configure_bounds(
    void*,
    void*,
    S32,
    S32) -> void {}

auto Platform::Wayland::XdgShell::on_toplevel_wm_capabilities(
    void*,
    void*,
    void*) -> void {}
